#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Check or resync the prompts-data.js mirror.

js/prompts-data.js holds a verbatim copy of every file in prompts/, because
browsers block fetch() on file:// and the site has to run by opening
index.html from disk. Nothing in the site enforces that the two copies
agree. If they drift, the page silently serves the stale copy while the .md
file that looks authoritative is not what anyone reads. This script is the
check that catches it.

    python tools/prompts-mirror.py            check, exit 1 on any problem
    python tools/prompts-mirror.py --sync     rewrite the data file from source

It also owns the share pages in p/, one per visible prompt. A link renderer
never sees the #/slug part of a URL and runs no JavaScript, so every hash
route looks like index.html to it. Each share page is a real address carrying
that prompt's sharing tags, with a meta refresh on to the prompt. They are
generated from the same frontmatter, written by --sync and compared byte for
byte by the check, so they cannot drift from the prompts either.

This is a maintenance tool, not part of the site. It never runs in a
browser, is not loaded by index.html, and is not a build step: delete it and
the site is unchanged. It has no third-party dependencies, only the Python
standard library, so it does not breach the project's no-dependency rule.
See docs/PRD.md sections 12, 29, 30, and 32a.
"""

import html
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'js', 'prompts-data.js')
PROMPTS = os.path.join(ROOT, 'prompts')
SHARE = os.path.join(ROOT, 'p')

# The canonical address, recorded in docs/PRD.md section 17. og:url has to
# be absolute, so it is written here rather than derived from anything.
SITE_URL = 'https://azqato.github.io/prompts/'
SITE_NAME = "Azqato's Prompts"

# A share page left behind by a removed or renamed prompt stays published,
# because once a link has been pasted it is a public address (PRD 32). The
# check accepts it only when it has been rewritten as a retired page and
# carries this marker, so a forgotten page cannot pass as a deliberate one.
RETIRED_MARKER = '<!-- retired:'

# Sharing budgets from docs/PRD.md section 32a. Past the target is reported,
# past the ceiling fails.
TITLE_TARGET, TITLE_CEILING = 60, 70
DESC_TARGET, DESC_CEILING = 150, 200


def read(path):
    """Read UTF-8, normalizing every line ending to LF.

    The normalization is not cosmetic, it is what makes the comparison
    correct. This repository stores LF and has no .gitattributes, while
    core.autocrlf is true by default on Windows, so a fresh clone puts CRLF
    in the working tree. The raw values inside prompts-data.js are JSON
    escapes rather than real line breaks, so git never rewrites them and
    they stay LF forever. Comparing the two literally would report drift on
    every prompt in a fresh Windows clone with nothing actually wrong.

    Line endings are a property of the checkout, not of the content, so they
    are normalized away on both sides. Leaving newline at its default gives
    universal-newline translation, which is exactly that normalization.
    Writing is done with newline='' so nothing is translated back on the way
    out and the data file is always LF.
    """
    return io.open(path, encoding='utf-8').read()


def write(path, text):
    io.open(path, 'w', encoding='utf-8', newline='').write(text)


def load_data():
    """Return (prologue, entries, epilogue) from js/prompts-data.js."""
    src = read(DATA)
    start = src.index('[')
    end = src.rindex(']') + 1
    return src[:start], json.loads(src[start:end]), src[end:]


def source_slugs():
    return sorted(
        name[:-3] for name in os.listdir(PROMPTS)
        if name.endswith('.md')
    )


def frontmatter(raw):
    fm = re.match(r'^---\r?\n(.*?)\r?\n---\r?\n', raw, re.S)
    if not fm:
        return None
    return dict(
        (m.group(1).lower(), m.group(2).strip())
        for m in re.finditer(r'^([A-Za-z0-9_-]+):\s*(.*)$', fm.group(1), re.M)
    )


def is_hidden(fields):
    # Mirrors parsePrompt() in js/script.js. Hidden prompts get no share page.
    return re.match(r'^(true|yes|1)$', fields.get('hidden', ''), re.I) is not None


def share_page(slug, fields):
    """The exact bytes of p/<slug>.html for one prompt."""
    # Attributes are double-quoted, so only the double quote needs escaping
    # there. Leaving apostrophes literal keeps the tags readable to scrapers.
    e = lambda s: html.escape(s, quote=False).replace('"', '&quot;')
    title = fields['title']
    desc = fields['description']
    target = '../index.html#/' + slug
    return '\n'.join([
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '  <meta charset="UTF-8">',
        '  <!-- Generated by tools/prompts-mirror.py from prompts/%s.md. Do not' % slug,
        '       edit by hand: change the .md file and run the script with --sync. -->',
        '  <title>%s - %s</title>' % (e(title), e(SITE_NAME)),
        '  <meta name="description" content="%s">' % e(desc),
        '  <meta property="og:title" content="%s">' % e(title),
        '  <meta property="og:description" content="%s">' % e(desc),
        '  <meta property="og:url" content="%s">' % e(SITE_URL + 'p/' + slug + '.html'),
        '  <meta property="og:type" content="website">',
        '  <meta property="og:site_name" content="%s">' % e(SITE_NAME),
        '  <meta name="twitter:card" content="summary">',
        '  <meta http-equiv="Content-Security-Policy" content="default-src \'none\'; base-uri \'none\'; form-action \'none\'">',
        '  <meta http-equiv="refresh" content="0; url=%s">' % e(target),
        '</head>',
        '<body>',
        '  <p><a href="%s">%s</a>, on %s.</p>' % (e(target), e(title), e(SITE_NAME)),
        '</body>',
        '</html>',
        '',
    ])


def expected_share_pages(entries):
    pages = {}
    for entry in entries:
        fields = frontmatter(entry['raw'])
        if fields and 'title' in fields and 'description' in fields and not is_hidden(fields):
            pages[entry['slug']] = share_page(entry['slug'], fields)
    return pages


def existing_share_pages():
    if not os.path.isdir(SHARE):
        return []
    return sorted(name[:-5] for name in os.listdir(SHARE) if name.endswith('.html'))


def check_sharing(entries, problems, notes):
    expected = expected_share_pages(entries)
    for slug in existing_share_pages():
        if slug not in expected:
            if RETIRED_MARKER not in read(os.path.join(SHARE, slug + '.html')):
                problems.append('share page with no visible prompt: p/%s.html. Retire it '
                                '(docs/PRD.md section 32a), never delete it' % slug)
    for slug, page in sorted(expected.items()):
        path = os.path.join(SHARE, slug + '.html')
        if not os.path.exists(path):
            problems.append('missing share page: p/%s.html' % slug)
        elif read(path) != page:
            problems.append('DRIFT: p/%s.html does not match its prompt' % slug)

    for entry in entries:
        fields = frontmatter(entry['raw']) or {}
        title, desc = fields.get('title', ''), fields.get('description', '')
        slug = entry['slug']
        if len(title) > TITLE_CEILING:
            problems.append('prompts/%s.md title is %d characters, over %d' % (slug, len(title), TITLE_CEILING))
        elif len(title) > TITLE_TARGET:
            notes.append('prompts/%s.md title is %d characters, over the %d target' % (slug, len(title), TITLE_TARGET))
        if len(desc) > DESC_CEILING:
            problems.append('prompts/%s.md description is %d characters, over %d' % (slug, len(desc), DESC_CEILING))
        elif len(desc) > DESC_TARGET:
            notes.append('prompts/%s.md description is %d characters, over the %d target' % (slug, len(desc), DESC_TARGET))
        if desc and not desc.endswith('.'):
            problems.append('prompts/%s.md description does not end on a full stop' % slug)
        if SITE_NAME in title:
            problems.append('prompts/%s.md title repeats the site name' % slug)


def render(entries):
    """Serialize entries in the file's existing two-space-indented style."""
    body = ',\n'.join(
        '  ' + json.dumps(e, ensure_ascii=False, indent=2).replace('\n', '\n  ')
        for e in entries
    )
    return '[\n' + body + '\n]'


def check():
    problems = []
    notes = []
    prologue, entries, epilogue = load_data()

    data_slugs = [e['slug'] for e in entries]
    files = source_slugs()

    for slug in sorted(set(data_slugs)):
        if data_slugs.count(slug) > 1:
            problems.append('duplicate entry in prompts-data.js: %s' % slug)
    for slug in sorted(set(data_slugs) - set(files)):
        problems.append('entry with no source file: prompts/%s.md is missing' % slug)
    for slug in sorted(set(files) - set(data_slugs)):
        problems.append('source file with no entry: prompts/%s.md is not in prompts-data.js' % slug)

    for entry in entries:
        slug = entry['slug']
        path = os.path.join(PROMPTS, slug + '.md')
        if not os.path.exists(path):
            continue
        if read(path) != entry['raw']:
            problems.append('DRIFT: prompts/%s.md does not match its entry' % slug)

    # Frontmatter and structure the renderer depends on. parsePrompt() falls
    # back silently for each of these, so a missing one ships as a page
    # titled with its slug, or with an empty code block, rather than as an
    # error anyone would notice.
    for entry in entries:
        raw = entry['raw']
        fm = re.match(r'^---\r?\n(.*?)\r?\n---\r?\n', raw, re.S)
        if not fm:
            problems.append('prompts/%s.md has no frontmatter block' % entry['slug'])
            continue
        keys = re.findall(r'^([A-Za-z0-9_-]+):', fm.group(1), re.M)
        for required in ('title', 'description'):
            if required not in keys:
                problems.append('prompts/%s.md frontmatter has no %s' % (entry['slug'], required))
        if not re.search(r'```[^\n]*\n.*?```', raw[fm.end():], re.S):
            problems.append('prompts/%s.md has no fenced prompt block' % entry['slug'])

    check_sharing(entries, problems, notes)
    for note in notes:
        print('note: ' + note)

    if problems:
        print('FAIL: %d problem(s)' % len(problems))
        for problem in problems:
            print('  - ' + problem)
        print('')
        print('Run with --sync to rewrite prompts-data.js and p/*.html from prompts/*.md.')
        return 1

    print('OK: %d prompt(s) mirrored, no orphans, all frontmatter present, '
          'share pages current.' % len(entries))
    for slug in data_slugs:
        print('  %s' % slug)
    return 0


def sync():
    prologue, entries, epilogue = load_data()
    files = source_slugs()

    known = set(e['slug'] for e in entries)
    missing = [s for s in files if s not in known]
    orphans = [e['slug'] for e in entries if e['slug'] not in files]

    if orphans:
        print('Refusing to sync. These entries have no source file:')
        for slug in orphans:
            print('  - %s' % slug)
        print('')
        print('Deleting a prompt is a deliberate act with a documented procedure')
        print('(docs/PRD.md section 12, "Removing Prompts"). Remove the entry by')
        print('hand so the README and the patch notes are updated in the same pass.')
        return 1

    changed = []
    for entry in entries:
        raw = read(os.path.join(PROMPTS, entry['slug'] + '.md'))
        if raw != entry['raw']:
            entry['raw'] = raw
            changed.append(entry['slug'])

    # New prompts append, because array order is display order and a new
    # prompt belongs last in the sidebar. See docs/PRD.md section 12 step 4.
    for slug in missing:
        entries.append({'slug': slug, 'raw': read(os.path.join(PROMPTS, slug + '.md'))})

    # Share pages are rewritten only where they differ, and never deleted.
    # A page whose prompt has gone is left for the check to report, because
    # retiring a public address is a decision, not a cleanup.
    pages = []
    for slug, page in sorted(expected_share_pages(entries).items()):
        path = os.path.join(SHARE, slug + '.html')
        if not os.path.exists(path) or read(path) != page:
            if not os.path.isdir(SHARE):
                os.makedirs(SHARE)
            write(path, page)
            pages.append(slug)

    if not changed and not missing and not pages:
        print('Nothing to do. Already in sync.')
        return 0

    if changed or missing:
        write(DATA, prologue + render(entries) + epilogue)
    for slug in changed:
        print('resynced: %s' % slug)
    for slug in missing:
        print('added:    %s' % slug)
    for slug in pages:
        print('share:    p/%s.html' % slug)
    print('')
    print('Written. Remember the rest of the procedure:')
    print('  - update README.md if the prompt list changed')
    print('  - add a docs/PATCHNOTES.md entry and a version history row')
    print('  - open index.html from disk and check the page')
    return 0


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == '--sync':
        sys.exit(sync())
    if len(sys.argv) > 1:
        print(__doc__)
        sys.exit(2)
    sys.exit(check())
